public with sharing class Opportunity_CC {
    
    public String OpportunityNextStep { get; set; }

    public String OpportunityLeadSource { get; set; }

    public String OpportunityType { get; set; }

    public String OpportunityAccountId { get; set; }

    public String OpportunityIsPrivate { get; set; }

    public String OpportunityAmount { get; set; }
    public String OpportunityName { get; set; }
   
    
    public String getOpportunity() {
        return null;
    }




    public PageReference Cancel() {
        return null;
    }


    public PageReference SaveandNew() {
        return null;
    }


    public PageReference Save() {
        return null;
    }

}